version: "3.8"
services:
  master:
    container_name: "master-node"
    build:
      context: "."
      target: "deploy"
      args:
        ENABLE_CMAKE: "true"
        ENABLE_BOOST: "true"
        ENABLE_TBB: "true"
        ENABLE_NINJA: "true"
    entrypoint: [
      "master-node",
      "--name",
      "master",
      "--http-port",
      "80",
      "--comm-port",
      "6000",
      "--http-workers",
      "3",
      "--comm-workers",
      "3"
    ]
    ports:
      - "80:8000" # master http port
    networks:
      distr-systems-hw:
        ipv4_address: "192.168.0.100"

networks:
  distr-systems-hw:
    driver: "bridge"
    ipam:
      config:
        - subnet: "192.168.0.0/24"
          gateway: "192.168.0.1"
